# The class to store the base_159 alphabet
class CreateTreeEncoding < ActiveRecord::Migration
  def self.up
    create_table :tree_encodings, :primary_key => :deci do |t|
      t.column :code, :char
    end
    
    execute( "insert into tree_encodings(deci, code) values(0,'0')" )
    execute( "insert into tree_encodings(deci, code) values(1,'1')" )
    execute( "insert into tree_encodings(deci, code) values(2,'2')" )
    execute( "insert into tree_encodings(deci, code) values(3,'3')" )
    execute( "insert into tree_encodings(deci, code) values(4,'4')" )
    execute( "insert into tree_encodings(deci, code) values(5,'5')" )
    execute( "insert into tree_encodings(deci, code) values(6,'6')" )
    execute( "insert into tree_encodings(deci, code) values(7,'7')" )
    execute( "insert into tree_encodings(deci, code) values(8,'8')" )
    execute( "insert into tree_encodings(deci, code) values(9,'9')" )
    execute( "insert into tree_encodings(deci, code) values(10,':')" )
    execute( "insert into tree_encodings(deci, code) values(11,';')" )
    execute( "insert into tree_encodings(deci, code) values(12,'A')" )
    execute( "insert into tree_encodings(deci, code) values(13,'B')" )
    execute( "insert into tree_encodings(deci, code) values(14,'C')" )
    execute( "insert into tree_encodings(deci, code) values(15,'D')" )
    execute( "insert into tree_encodings(deci, code) values(16,'E')" )
    execute( "insert into tree_encodings(deci, code) values(17,'F')" )
    execute( "insert into tree_encodings(deci, code) values(18,'G')" )
    execute( "insert into tree_encodings(deci, code) values(19,'H')" )
    execute( "insert into tree_encodings(deci, code) values(20,'I')" )
    execute( "insert into tree_encodings(deci, code) values(21,'J')" )
    execute( "insert into tree_encodings(deci, code) values(22,'K')" )
    execute( "insert into tree_encodings(deci, code) values(23,'L')" )
    execute( "insert into tree_encodings(deci, code) values(24,'M')" )
    execute( "insert into tree_encodings(deci, code) values(25,'N')" )
    execute( "insert into tree_encodings(deci, code) values(26,'O')" )
    execute( "insert into tree_encodings(deci, code) values(27,'P')" )
    execute( "insert into tree_encodings(deci, code) values(28,'Q')" )
    execute( "insert into tree_encodings(deci, code) values(29,'R')" )
    execute( "insert into tree_encodings(deci, code) values(30,'S')" )
    execute( "insert into tree_encodings(deci, code) values(31,'T')" )
    execute( "insert into tree_encodings(deci, code) values(32,'U')" )
    execute( "insert into tree_encodings(deci, code) values(33,'V')" )
    execute( "insert into tree_encodings(deci, code) values(34,'W')" )
    execute( "insert into tree_encodings(deci, code) values(35,'X')" )
    execute( "insert into tree_encodings(deci, code) values(36,'Y')" )
    execute( "insert into tree_encodings(deci, code) values(37,'Z')" )
    execute( "insert into tree_encodings(deci, code) values(38,'a')" )
    execute( "insert into tree_encodings(deci, code) values(39,'b')" )
    execute( "insert into tree_encodings(deci, code) values(40,'c')" )
    execute( "insert into tree_encodings(deci, code) values(41,'d')" )
    execute( "insert into tree_encodings(deci, code) values(42,'e')" )
    execute( "insert into tree_encodings(deci, code) values(43,'f')" )
    execute( "insert into tree_encodings(deci, code) values(44,'g')" )
    execute( "insert into tree_encodings(deci, code) values(45,'h')" )
    execute( "insert into tree_encodings(deci, code) values(46,'i')" )
    execute( "insert into tree_encodings(deci, code) values(47,'j')" )
    execute( "insert into tree_encodings(deci, code) values(48,'k')" )
    execute( "insert into tree_encodings(deci, code) values(49,'l')" )
    execute( "insert into tree_encodings(deci, code) values(50,'m')" )
    execute( "insert into tree_encodings(deci, code) values(51,'n')" )
    execute( "insert into tree_encodings(deci, code) values(52,'o')" )
    execute( "insert into tree_encodings(deci, code) values(53,'p')" )
    execute( "insert into tree_encodings(deci, code) values(54,'q')" )
    execute( "insert into tree_encodings(deci, code) values(55,'r')" )
    execute( "insert into tree_encodings(deci, code) values(56,'s')" )
    execute( "insert into tree_encodings(deci, code) values(57,'t')" )
    execute( "insert into tree_encodings(deci, code) values(58,'u')" )
    execute( "insert into tree_encodings(deci, code) values(59,'v')" )
    execute( "insert into tree_encodings(deci, code) values(60,'w')" )
    execute( "insert into tree_encodings(deci, code) values(61,'x')" )
    execute( "insert into tree_encodings(deci, code) values(62,'y')" )
    execute( "insert into tree_encodings(deci, code) values(63,'z')" )
    execute( "insert into tree_encodings(deci, code) values(64,'¡')" )
    execute( "insert into tree_encodings(deci, code) values(65,'¢')" )
    execute( "insert into tree_encodings(deci, code) values(66,'£')" )
    execute( "insert into tree_encodings(deci, code) values(67,'¤')" )
    execute( "insert into tree_encodings(deci, code) values(68,'¥')" )
    execute( "insert into tree_encodings(deci, code) values(69,'¦')" )
    execute( "insert into tree_encodings(deci, code) values(70,'§')" )
    execute( "insert into tree_encodings(deci, code) values(71,'¨')" )
    execute( "insert into tree_encodings(deci, code) values(72,'©')" )
    execute( "insert into tree_encodings(deci, code) values(73,'ª')" )
    execute( "insert into tree_encodings(deci, code) values(74,'«')" )
    execute( "insert into tree_encodings(deci, code) values(75,'¬')" )
    execute( "insert into tree_encodings(deci, code) values(76,'­')" )
    execute( "insert into tree_encodings(deci, code) values(77,'®')" )
    execute( "insert into tree_encodings(deci, code) values(78,'¯')" )
    execute( "insert into tree_encodings(deci, code) values(79,'°')" )
    execute( "insert into tree_encodings(deci, code) values(80,'±')" )
    execute( "insert into tree_encodings(deci, code) values(81,'²')" )
    execute( "insert into tree_encodings(deci, code) values(82,'³')" )
    execute( "insert into tree_encodings(deci, code) values(83,'´')" )
    execute( "insert into tree_encodings(deci, code) values(84,'µ')" )
    execute( "insert into tree_encodings(deci, code) values(85,'¶')" )
    execute( "insert into tree_encodings(deci, code) values(86,'·')" )
    execute( "insert into tree_encodings(deci, code) values(87,'¸')" )
    execute( "insert into tree_encodings(deci, code) values(88,'¹')" )
    execute( "insert into tree_encodings(deci, code) values(89,'º')" )
    execute( "insert into tree_encodings(deci, code) values(90,'»')" )
    execute( "insert into tree_encodings(deci, code) values(91,'¼')" )
    execute( "insert into tree_encodings(deci, code) values(92,'½')" )
    execute( "insert into tree_encodings(deci, code) values(93,'¾')" )
    execute( "insert into tree_encodings(deci, code) values(94,'¿')" )
    execute( "insert into tree_encodings(deci, code) values(95,'À')" )
    execute( "insert into tree_encodings(deci, code) values(96,'Á')" )
    execute( "insert into tree_encodings(deci, code) values(97,'Â')" )
    execute( "insert into tree_encodings(deci, code) values(98,'Ã')" )
    execute( "insert into tree_encodings(deci, code) values(99,'Ä')" )
    execute( "insert into tree_encodings(deci, code) values(100,'Å')" )
    execute( "insert into tree_encodings(deci, code) values(101,'Æ')" )
    execute( "insert into tree_encodings(deci, code) values(102,'Ç')" )
    execute( "insert into tree_encodings(deci, code) values(103,'È')" )
    execute( "insert into tree_encodings(deci, code) values(104,'É')" )
    execute( "insert into tree_encodings(deci, code) values(105,'Ê')" )
    execute( "insert into tree_encodings(deci, code) values(106,'Ë')" )
    execute( "insert into tree_encodings(deci, code) values(107,'Ì')" )
    execute( "insert into tree_encodings(deci, code) values(108,'Í')" )
    execute( "insert into tree_encodings(deci, code) values(109,'Î')" )
    execute( "insert into tree_encodings(deci, code) values(110,'Ï')" )
    execute( "insert into tree_encodings(deci, code) values(111,'Ð')" )
    execute( "insert into tree_encodings(deci, code) values(112,'Ñ')" )
    execute( "insert into tree_encodings(deci, code) values(113,'Ò')" )
    execute( "insert into tree_encodings(deci, code) values(114,'Ó')" )
    execute( "insert into tree_encodings(deci, code) values(115,'Ô')" )
    execute( "insert into tree_encodings(deci, code) values(116,'Õ')" )
    execute( "insert into tree_encodings(deci, code) values(117,'Ö')" )
    execute( "insert into tree_encodings(deci, code) values(118,'×')" )
    execute( "insert into tree_encodings(deci, code) values(119,'Ø')" )
    execute( "insert into tree_encodings(deci, code) values(120,'Ù')" )
    execute( "insert into tree_encodings(deci, code) values(121,'Ú')" )
    execute( "insert into tree_encodings(deci, code) values(122,'Û')" )
    execute( "insert into tree_encodings(deci, code) values(123,'Ü')" )
    execute( "insert into tree_encodings(deci, code) values(124,'Ý')" )
    execute( "insert into tree_encodings(deci, code) values(125,'Þ')" )
    execute( "insert into tree_encodings(deci, code) values(126,'ß')" )
    execute( "insert into tree_encodings(deci, code) values(127,'à')" )
    execute( "insert into tree_encodings(deci, code) values(128,'á')" )
    execute( "insert into tree_encodings(deci, code) values(129,'â')" )
    execute( "insert into tree_encodings(deci, code) values(130,'ã')" )
    execute( "insert into tree_encodings(deci, code) values(131,'ä')" )
    execute( "insert into tree_encodings(deci, code) values(132,'å')" )
    execute( "insert into tree_encodings(deci, code) values(133,'æ')" )
    execute( "insert into tree_encodings(deci, code) values(134,'ç')" )
    execute( "insert into tree_encodings(deci, code) values(135,'è')" )
    execute( "insert into tree_encodings(deci, code) values(136,'é')" )
    execute( "insert into tree_encodings(deci, code) values(137,'ê')" )
    execute( "insert into tree_encodings(deci, code) values(138,'ë')" )
    execute( "insert into tree_encodings(deci, code) values(139,'ì')" )
    execute( "insert into tree_encodings(deci, code) values(140,'í')" )
    execute( "insert into tree_encodings(deci, code) values(141,'î')" )
    execute( "insert into tree_encodings(deci, code) values(142,'ï')" )
    execute( "insert into tree_encodings(deci, code) values(143,'ð')" )
    execute( "insert into tree_encodings(deci, code) values(144,'ñ')" )
    execute( "insert into tree_encodings(deci, code) values(145,'ò')" )
    execute( "insert into tree_encodings(deci, code) values(146,'ó')" )
    execute( "insert into tree_encodings(deci, code) values(147,'ô')" )
    execute( "insert into tree_encodings(deci, code) values(148,'õ')" )
    execute( "insert into tree_encodings(deci, code) values(149,'ö')" )
    execute( "insert into tree_encodings(deci, code) values(150,'÷')" )
    execute( "insert into tree_encodings(deci, code) values(151,'ø')" )
    execute( "insert into tree_encodings(deci, code) values(152,'ù')" )
    execute( "insert into tree_encodings(deci, code) values(153,'ú')" )
    execute( "insert into tree_encodings(deci, code) values(154,'û')" )
    execute( "insert into tree_encodings(deci, code) values(155,'ü')" )
    execute( "insert into tree_encodings(deci, code) values(156,'ý')" )
    execute( "insert into tree_encodings(deci, code) values(157,'þ')" )
    execute( "insert into tree_encodings(deci, code) values(158,'ÿ')" )
  end
  
  def self.down
    drop_table :tree_encodings
  end
end

class CreateHierarchicalObjects < ActiveRecord::Migration
  def self.up
    create_table :hierarchical_objects do |t|
      t.column :parent_id, :uint
      t.column :sortkey, :text
    end
  end
  
  def self.down
    drop_table :hierarchical_objects
  end
end
