# The class to store the base_159 alphabet
class CreateTreeEncoding < ActiveRecord::Migration
  def self.up
    create_table :tree_encodings, :primary_key => :deci do |t|
      t.column :code, :char
    end

    execute( "insert into tree_encodings(code, deci) values('0', 0)")
    execute( "insert into tree_encodings(code, deci) values('1', 1)")
    execute( "insert into tree_encodings(code, deci) values('2', 2)")
    execute( "insert into tree_encodings(code, deci) values('3', 3)")
    execute( "insert into tree_encodings(code, deci) values('4', 4)")
    execute( "insert into tree_encodings(code, deci) values('5', 5)")
    execute( "insert into tree_encodings(code, deci) values('6', 6)")
    execute( "insert into tree_encodings(code, deci) values('7', 7)")
    execute( "insert into tree_encodings(code, deci) values('8', 8)")
    execute( "insert into tree_encodings(code, deci) values('9', 9)")
    execute( "insert into tree_encodings(code, deci) values(':', 10)")
    execute( "insert into tree_encodings(code, deci) values(';', 11)")
    execute( "insert into tree_encodings(code, deci) values('Á', 12)")
    execute( "insert into tree_encodings(code, deci) values('Â', 13)")
    execute( "insert into tree_encodings(code, deci) values('à', 14)")
    execute( "insert into tree_encodings(code, deci) values('á', 15)")
    execute( "insert into tree_encodings(code, deci) values('â', 16)")
    execute( "insert into tree_encodings(code, deci) values('ã', 17)")
    execute( "insert into tree_encodings(code, deci) values('Ã', 18)")
    execute( "insert into tree_encodings(code, deci) values('À', 19)")
    execute( "insert into tree_encodings(code, deci) values('A', 20)")
    execute( "insert into tree_encodings(code, deci) values('a', 21)")
    execute( "insert into tree_encodings(code, deci) values('b', 22)")
    execute( "insert into tree_encodings(code, deci) values('B', 23)")
    execute( "insert into tree_encodings(code, deci) values('ç', 24)")
    execute( "insert into tree_encodings(code, deci) values('C', 25)")
    execute( "insert into tree_encodings(code, deci) values('c', 26)")
    execute( "insert into tree_encodings(code, deci) values('Ç', 27)")
    execute( "insert into tree_encodings(code, deci) values('d', 28)")
    execute( "insert into tree_encodings(code, deci) values('ð', 29)")
    execute( "insert into tree_encodings(code, deci) values('Ð', 30)")
    execute( "insert into tree_encodings(code, deci) values('D', 31)")
    execute( "insert into tree_encodings(code, deci) values('e', 32)")
    execute( "insert into tree_encodings(code, deci) values('E', 33)")
    execute( "insert into tree_encodings(code, deci) values('è', 34)")
    execute( "insert into tree_encodings(code, deci) values('È', 35)")
    execute( "insert into tree_encodings(code, deci) values('É', 36)")
    execute( "insert into tree_encodings(code, deci) values('Ê', 37)")
    execute( "insert into tree_encodings(code, deci) values('Ë', 38)")
    execute( "insert into tree_encodings(code, deci) values('ë', 39)")
    execute( "insert into tree_encodings(code, deci) values('ê', 40)")
    execute( "insert into tree_encodings(code, deci) values('é', 41)")
    execute( "insert into tree_encodings(code, deci) values('F', 42)")
    execute( "insert into tree_encodings(code, deci) values('f', 43)")
    execute( "insert into tree_encodings(code, deci) values('G', 44)")
    execute( "insert into tree_encodings(code, deci) values('g', 45)")
    execute( "insert into tree_encodings(code, deci) values('h', 46)")
    execute( "insert into tree_encodings(code, deci) values('H', 47)")
    execute( "insert into tree_encodings(code, deci) values('Ï', 48)")
    execute( "insert into tree_encodings(code, deci) values('Ì', 49)")
    execute( "insert into tree_encodings(code, deci) values('ï', 50)")
    execute( "insert into tree_encodings(code, deci) values('î', 51)")
    execute( "insert into tree_encodings(code, deci) values('í', 52)")
    execute( "insert into tree_encodings(code, deci) values('Î', 53)")
    execute( "insert into tree_encodings(code, deci) values('ì', 54)")
    execute( "insert into tree_encodings(code, deci) values('Í', 55)")
    execute( "insert into tree_encodings(code, deci) values('I', 56)")
    execute( "insert into tree_encodings(code, deci) values('i', 57)")
    execute( "insert into tree_encodings(code, deci) values('J', 58)")
    execute( "insert into tree_encodings(code, deci) values('j', 59)")
    execute( "insert into tree_encodings(code, deci) values('k', 60)")
    execute( "insert into tree_encodings(code, deci) values('K', 61)")
    execute( "insert into tree_encodings(code, deci) values('l', 62)")
    execute( "insert into tree_encodings(code, deci) values('L', 63)")
    execute( "insert into tree_encodings(code, deci) values('m', 64)")
    execute( "insert into tree_encodings(code, deci) values('M', 65)")
    execute( "insert into tree_encodings(code, deci) values('N', 66)")
    execute( "insert into tree_encodings(code, deci) values('n', 67)")
    execute( "insert into tree_encodings(code, deci) values('Ñ', 68)")
    execute( "insert into tree_encodings(code, deci) values('ñ', 69)")
    execute( "insert into tree_encodings(code, deci) values('Ô', 70)")
    execute( "insert into tree_encodings(code, deci) values('Ó', 71)")
    execute( "insert into tree_encodings(code, deci) values('Ò', 72)")
    execute( "insert into tree_encodings(code, deci) values('ô', 73)")
    execute( "insert into tree_encodings(code, deci) values('Õ', 74)")
    execute( "insert into tree_encodings(code, deci) values('O', 75)")
    execute( "insert into tree_encodings(code, deci) values('õ', 76)")
    execute( "insert into tree_encodings(code, deci) values('o', 77)")
    execute( "insert into tree_encodings(code, deci) values('ò', 78)")
    execute( "insert into tree_encodings(code, deci) values('ó', 79)")
    execute( "insert into tree_encodings(code, deci) values('p', 80)")
    execute( "insert into tree_encodings(code, deci) values('P', 81)")
    execute( "insert into tree_encodings(code, deci) values('Q', 82)")
    execute( "insert into tree_encodings(code, deci) values('q', 83)")
    execute( "insert into tree_encodings(code, deci) values('R', 84)")
    execute( "insert into tree_encodings(code, deci) values('r', 85)")
    execute( "insert into tree_encodings(code, deci) values('S', 86)")
    execute( "insert into tree_encodings(code, deci) values('s', 87)")
    execute( "insert into tree_encodings(code, deci) values('T', 88)")
    execute( "insert into tree_encodings(code, deci) values('t', 89)")
    execute( "insert into tree_encodings(code, deci) values('û', 90)")
    execute( "insert into tree_encodings(code, deci) values('Û', 91)")
    execute( "insert into tree_encodings(code, deci) values('ú', 92)")
    execute( "insert into tree_encodings(code, deci) values('ù', 93)")
    execute( "insert into tree_encodings(code, deci) values('Ú', 94)")
    execute( "insert into tree_encodings(code, deci) values('u', 95)")
    execute( "insert into tree_encodings(code, deci) values('Ù', 96)")
    execute( "insert into tree_encodings(code, deci) values('U', 97)")
    execute( "insert into tree_encodings(code, deci) values('v', 98)")
    execute( "insert into tree_encodings(code, deci) values('V', 99)")
    execute( "insert into tree_encodings(code, deci) values('W', 100)")
    execute( "insert into tree_encodings(code, deci) values('w', 101)")
    execute( "insert into tree_encodings(code, deci) values('x', 102)")
    execute( "insert into tree_encodings(code, deci) values('X', 103)")
    execute( "insert into tree_encodings(code, deci) values('Y', 104)")
    execute( "insert into tree_encodings(code, deci) values('Ý', 105)")
    execute( "insert into tree_encodings(code, deci) values('Ü', 106)")
    execute( "insert into tree_encodings(code, deci) values('ý', 107)")
    execute( "insert into tree_encodings(code, deci) values('y', 108)")
    execute( "insert into tree_encodings(code, deci) values('ü', 109)")
    execute( "insert into tree_encodings(code, deci) values('z', 110)")
    execute( "insert into tree_encodings(code, deci) values('Z', 111)")
    execute( "insert into tree_encodings(code, deci) values('Å', 112)")
    execute( "insert into tree_encodings(code, deci) values('å', 113)")
    execute( "insert into tree_encodings(code, deci) values('Ä', 114)")
    execute( "insert into tree_encodings(code, deci) values('Æ', 115)")
    execute( "insert into tree_encodings(code, deci) values('æ', 116)")
    execute( "insert into tree_encodings(code, deci) values('ä', 117)")
    execute( "insert into tree_encodings(code, deci) values('ö', 118)")
    execute( "insert into tree_encodings(code, deci) values('Ö', 119)")
    execute( "insert into tree_encodings(code, deci) values('¡', 120)")
    execute( "insert into tree_encodings(code, deci) values('¢', 121)")
    execute( "insert into tree_encodings(code, deci) values('£', 122)")
    execute( "insert into tree_encodings(code, deci) values('¤', 123)")
    execute( "insert into tree_encodings(code, deci) values('¥', 124)")
    execute( "insert into tree_encodings(code, deci) values('¦', 125)")
    execute( "insert into tree_encodings(code, deci) values('§', 126)")
    execute( "insert into tree_encodings(code, deci) values('¨', 127)")
    execute( "insert into tree_encodings(code, deci) values('©', 128)")
    execute( "insert into tree_encodings(code, deci) values('ª', 129)")
    execute( "insert into tree_encodings(code, deci) values('«', 130)")
    execute( "insert into tree_encodings(code, deci) values('¬', 131)")
    execute( "insert into tree_encodings(code, deci) values('­', 132)")
    execute( "insert into tree_encodings(code, deci) values('®', 133)")
    execute( "insert into tree_encodings(code, deci) values('¯', 134)")
    execute( "insert into tree_encodings(code, deci) values('°', 135)")
    execute( "insert into tree_encodings(code, deci) values('±', 136)")
    execute( "insert into tree_encodings(code, deci) values('²', 137)")
    execute( "insert into tree_encodings(code, deci) values('³', 138)")
    execute( "insert into tree_encodings(code, deci) values('´', 139)")
    execute( "insert into tree_encodings(code, deci) values('µ', 140)")
    execute( "insert into tree_encodings(code, deci) values('¶', 141)")
    execute( "insert into tree_encodings(code, deci) values('·', 142)")
    execute( "insert into tree_encodings(code, deci) values('¸', 143)")
    execute( "insert into tree_encodings(code, deci) values('¹', 144)")
    execute( "insert into tree_encodings(code, deci) values('º', 145)")
    execute( "insert into tree_encodings(code, deci) values('»', 146)")
    execute( "insert into tree_encodings(code, deci) values('¼', 147)")
    execute( "insert into tree_encodings(code, deci) values('½', 148)")
    execute( "insert into tree_encodings(code, deci) values('¾', 149)")
    execute( "insert into tree_encodings(code, deci) values('¿', 150)")
    execute( "insert into tree_encodings(code, deci) values('×', 151)")
    execute( "insert into tree_encodings(code, deci) values('Ø', 152)")
    execute( "insert into tree_encodings(code, deci) values('ø', 153)")
    execute( "insert into tree_encodings(code, deci) values('Þ', 154)")
    execute( "insert into tree_encodings(code, deci) values('þ', 155)")
    execute( "insert into tree_encodings(code, deci) values('ß', 156)")
    execute( "insert into tree_encodings(code, deci) values('÷', 157)")
    execute( "insert into tree_encodings(code, deci) values('ÿ', 158)")
    
  end
  
  def self.down
    drop_table :tree_encodings
  end
end

class CreateHierarchicalObjects < ActiveRecord::Migration
  def self.up
    create_table :hierarchical_objects do |t|
      t.column :parent_id, :uint
      t.column :sortkey, :text
    end
  end
  
  def self.down
    drop_table :hierarchical_objects
  end
end
